#!/bin/bash

if [[ $# -lt 3 || $# -gt 3 ]]; then
	echo "Usage: ./network-analyser <Pid> <output-pcap-file-name> <time_duration>"
	exit 0
fi

output_directory="/home/user/FinalLogs/"
base_file=${2%?????}

mkdir -p "${output_directory}${base_file}"
#p=$(cat ~/.passwd)
#echo "$p"|sudo -S  nsenter -t "$1" -n tshark -i any -f "tcp" -w /tmp/"$2"

#echo "$p"|sudo -S  mv /tmp/"$2" ~/GRPC/Go/Pcaps/

#echo "$p"|sudo -S chmod 777 ~/GRPC/Go/Pcaps/"$2"

p=$(cat ~/.passwd)
echo "$p"|sudo -S nsenter -t "$1" -n sar -n DEV 1 $3 -o "${output_directory}${base_file}/${base_file}-DEV" &
echo "$p"|sudo -S nsenter -t "$1" -n sar -n EDEV 1 $3 -o "${output_directory}${base_file}/${base_file}-EDEV" & 
echo "$p"|sudo -S nsenter -t "$1" -n sar -n ETCP 1 $3 -o "${output_directory}${base_file}/${base_file}-ETCP" 

echo "All sar monitoring complete"




